INSERT INTO menu_items (name, description, price, is_available, category, tags, image) VALUES 
('Small Plastic Chair', 'Possimus dignissimos libero.', 849, true, 'Electronics', 'proper,adorable', 'https://loremflickr.com/300/300/food'),
('Electronic Plastic Ball', 'Omnis optio minus facere amet accusantium sapiente quo repellendus sed.', 348, true, 'Industrial', 'unkempt,inborn,negative,enchanted', 'https://loremflickr.com/300/300/food'),
('Gorgeous Granite Car', 'Unde quaerat nulla quas fuga occaecati.', 977, true, 'Home', 'grave', 'https://loremflickr.com/300/300/food'),
('Tasty Soft Shirt', 'Molestiae harum mollitia.', 891, false, 'Automotive', 'trusting,prickly,clear,deafening,svelte,haunting', 'https://loremflickr.com/300/300/food'),
('Practical Soft Salad', 'Nulla praesentium praesentium harum labore fugiat.', 784, true, 'Shoes', 'vigilant,creative,sleepy,vicious,putrid,waterlogged,bold', 'https://loremflickr.com/300/300/food'),
('Ergonomic Concrete Salad', 'Fugiat deleniti aut facere vero.', 248, true, 'Movies', 'mixed,separate,gullible,immaterial,excitable,inexperienced,well-made', 'https://loremflickr.com/300/300/food'),
('Bespoke Wooden Bike', 'Officiis atque illum laboriosam rem laborum dolorem.', 443, true, 'Computers', 'busy,blond,sinful,fickle,unusual,educated,distinct,weak,international', 'https://loremflickr.com/300/300/food'),
('Electronic Steel Shirt', 'Similique ipsam saepe laboriosam quisquam ex aperiam vitae adipisci facilis.', 624, true, 'Automotive', 'shy', 'https://loremflickr.com/300/300/food'),
('Elegant Soft Salad', 'Minus architecto optio sed.', 946, false, 'Health', 'damaged,wilted,piercing,well-off,uncomfortable,pointless,brisk', 'https://loremflickr.com/300/300/food'),
('Oriental Steel Tuna', 'Quam possimus corporis tempore accusantium non cum.', 619, false, 'Tools', 'leafy,rare', 'https://loremflickr.com/300/300/food'),
('Refined Fresh Tuna', 'Corporis dolorem non velit.', 622, true, 'Home', 'deficient,woeful', 'https://loremflickr.com/300/300/food'),
('Unbranded Cotton Keyboard', 'Facilis aliquid voluptas illum optio nostrum officiis eius.', 505, false, 'Garden', 'inferior', 'https://loremflickr.com/300/300/food'),
('Modern Plastic Keyboard', 'Voluptatem odit explicabo nemo rem ipsa cumque.', 944, true, 'Games', 'mundane,milky,square,knowing,natural', 'https://loremflickr.com/300/300/food'),
('Fantastic Granite Ball', 'Numquam voluptatum eveniet in quisquam delectus a est.', 427, true, 'Tools', 'definitive,misguided,single,tricky,frozen', 'https://loremflickr.com/300/300/food'),
('Electronic Cotton Tuna', 'Ratione quos adipisci qui totam sint quae.', 414, true, 'Games', 'thorough,glittering,heavy', 'https://loremflickr.com/300/300/food'),
('Licensed Concrete Hat', 'Eius aperiam mollitia.', 355, false, 'Beauty', 'pungent,speedy,nice,tepid,green,warmhearted,unfolded', 'https://loremflickr.com/300/300/food'),
('Awesome Metal Table', 'Maiores voluptatem aperiam velit vero.', 869, false, 'Electronics', 'standard', 'https://loremflickr.com/300/300/food'),
('Gorgeous Wooden Fish', 'Ea provident voluptates eos soluta facere.', 516, false, 'Health', 'incomparable,striking,altruistic,content,quintessential,periodic,shrill,sardonic,incompatible', 'https://loremflickr.com/300/300/food'),
('Tasty Metal Computer', 'Voluptate consequatur tenetur fuga vel facere quo reiciendis perferendis animi.', 790, true, 'Shoes', 'dramatic,roasted', 'https://loremflickr.com/300/300/food'),
('Luxurious Bronze Table', 'Blanditiis provident id libero illum.', 1, true, 'Books', 'impish', 'https://loremflickr.com/300/300/food');