#!/bin/bash

#TODO: dynamic main monitor setup
MAINMONITOR=eDP-1

function ActivateExternal {
    echo "Switching to DUALWIELD"
     xrandr --output DP-0 --mode 2560x1440 --output eDP-1 --below DP1
     nitrogen --restore &
     ~/scripts/polybar/lauch.sh
     i3-msg "workspace 1, move workspace to output DP-0"
     i3-msg "workspace 2, move workspace to output DP-0"
     i3-msg "workspace 3, move workspace to output DP-0"
     i3-msg "workspace 4, move workspace to output DP-0"
     i3-msg "workspace 5, move workspace to output eDP-1"
     i3-msg "workspace 6, move workspace to output eDP-1"



    MAINMONITOR=DP-0
}
function DeactivateExternal {
    echo "Switching to SINGLE"
    xrandr --output DP-0 --off --output eDP-1 --auto
    ~/scripts/polybar/lauch.sh
    MAINMONITOR=eDP-1
}

function ExternalActive {
    [ $MAINMONITOR = "DP-0" ]
}
function ExternalConnected {
    ! xrandr | grep "^DP-0" | grep disconnected
}

while true
do
    if ! ExternalActive && ExternalConnected
    then
        ActivateExternal
    fi

    if ExternalActive && ! ExternalConnected
    then
        DeactivateExternal
    fi

    sleep 1s
done
